addReviewers: true

addAssignees: author

numberOfReviewers: 2

useReviewGroups: false

reviewers:
  - ikki-kki
  - DiveDiFF
  - yongsk0066
  - kimjeongwonn
  - saengmotmi
  - jihunhong
  - takethisbus
  - KimJeongHyun
  - cb-bang
  - rjcnd105

useAssigneeGroups: false
