addReviewers: true

addAssignees: author

numberOfReviewers: 2

useReviewGroups: false

reviewers:
  - JeongminSung
  - DiveDiFF
  - yongsk0066
  - kimjeongwonn
  - saengmotmi
  - Yuddomack

useAssigneeGroups: false
