addReviewers: true

addAssignees: author

numberOfReviewers: 2

useReviewGroups: false

reviewers:
  - yongsk0066
  - kimjeongwonn
  - saengmotmi
  - DiveDiFF
  - jihunhong
  - takethisbus
  - KimJeongHyun
  - cb-bang
  - soonki-98
  - hazzzi

useAssigneeGroups: false
