name: 'Assign Reviewers'

on:
  pull_request:
    types:
      - opened
      - ready_for_review
    branches:
      - develop
      - feature/**

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign_config.yml'
